services:
  - type: web
    name: ai-home-staging
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    plan: free 